export interface UserResDto {
    id: number,
    userId: string,
    currentCompanyId: string,
    enabled: boolean,
    role: string,
    userNm: string,
    email: string,
    firstNm: string,
    lastNm: string,
    isDeleted: boolean,
    isBlocked: boolean,
    countLoginFailed: number,
    createdDt: string,
    updatedDt: string,
}
